contact form for the portfolio
SamroodAli/curriculum-cr-training-contact-form pull request #1
Opened 2021-07-01 18:03 UTC by SamroodAli

Please review my code base for contact form
Make sure that:
Name field accepts up to 30 chars.
Email field accepts only emails.
Message field accepts up to 500 chars.
All fields have placeholder text.
All fields have the correct type.
A user cannot submit the form if one or more of the fields is empty.
Collect data by using the Formspree service.
In order to lay out the elements on the page you should use Flexbox.
You don't need to implement any functionality that requires JavaScript.
Thanks for your time and consideration

2021-07-01 21:52 UTC, KabohaJeanMark requested changes
Hi @SamroodAli, 

Good job so far!
I like how you have used fluid measurements like rem and % so that the project is very responsive. It has been fun to go through your project 👍🏾 

There are just a few issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._
- [x] - Please use the actual email input tag so that only real emails can be inputted.
- [x] - Please add required to all your form inputs so that only when all have had the right data inputted. this validation is key for getting the right information.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] - [OPTIONAL] Adding an actual license for this project.
- [ ] - [OPTIONAL] Adding information in the alt tags of images to improve accessibility by making it easy for screen readers hence improving inclusion.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-01 21:52 UTC, KabohaJeanMark commented on index.html
> +              type="text"
```suggestion
              type="email"
```
Please change the input type to email.
This will help with validation so that only proper email addresses are put in that email field.

2021-07-01 21:52 UTC, KabohaJeanMark commented on index.html
> +          <img src="media/svg/github.svg" alt="" />
```suggestion
          <img src="media/svg/github.svg" alt="" />
```
```suggestion
          <img src="media/svg/github.svg" alt="github social media logo" />
```
[OPTIONAL]
- Please always add alt text to images so that it can help screen readers to read for improving the accessibility and inclusion of the website.

2021-07-01 21:52 UTC, KabohaJeanMark commented on index.html
> +            />
```suggestion
           required
            />
```
Perhaps you should consider adding required on all form inputs so that a user cannot submit the form if one or more of the fields is empty. This helps your form collect all useful information.

2021-07-01 21:52 UTC, KabohaJeanMark commented on css/main.css
> +  border-bottom: 1px solid rgba(158, 157, 156, 0.383) !important;
Please, kindly opt for another way for this code to be focused on.

Using !important should be avoided because it makes debugging more difficult by breaking the natural cascading in your stylesheets. When two conflicting declarations with the !important rule are applied to the same element, the declaration with a greater specificity will be applied.

Please check out this [Article on Specificity in Mozilla dev docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

2021-07-01 21:52 UTC, KabohaJeanMark commented on css/main.css
> +  margin-bottom: 1rem;
Awesome 😎  job using fluid measurements such as rem and percentage.
These really help with responsiveness since they change as the viewport changes unlike absolute measurements like pixels.

2021-07-01 21:52 UTC, KabohaJeanMark commented on MIT.md
> +## Copyright 2021, [YOUR NAME]
[OPTIONAL]
Perhaps you could please create an actual license for this project.
[GitHub Article on how to add a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

2021-07-02 18:07 UTC, SamroodAli commented
@KabohaJeanMark Thanks for reviewing my code. I have made the changes requested . I am requesting another review for the changes made. Happy weekend brother :+1:

2021-07-02 18:45 UTC, carlos-ssh approved these changes
Hi @SamroodAli, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-26 07:40 UTC, closed without merging